name: game_communityapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  lottie: ^3.1.3
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.2
  video_player: ^2.9.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_staggered_animations: ^1.1.1
  permission_handler: ^11.3.1
  chewie: ^1.8.5
  flutter_file_downloader: ^2.0.0
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/gaming_splash.json